<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <AssemblyName>AdoNetCore.AseClient.Benchmark</AssemblyName>
    <StartupObject>AdoNetCore.AseClient.Benchmark.Program</StartupObject>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0|AnyCPU'">
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);NET_CORE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageReference Include="Dapper" Version="1.60.6" />
    <PackageReference Include="System.Security.Permissions" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AdoNetCore.AseClient\AdoNetCore.AseClient.csproj" />
    <ProjectReference Include="..\AdoNetCore.AseClient.Tests\AdoNetCore.AseClient.Tests.csproj" />
  </ItemGroup>
</Project>
